### ISSUE TITLE
GUM TSV data format contains invalid data in "identity" column and uses reserved name for column

### ISSUE THREAD

**Issue by reckart** [amir-zeldes/gum#101]
When trying tp import https://raw.githubusercontent.com/amir-zeldes/gum/master/coref/gum/tsv/GUM_academic_art.tsv into INCEpTION, the process fails with an error indicating that a disambiguation ID is not used properly.

It appears that in the following line there is an error in the `identity` column. Instead of 

```
12-16	954-962	Zurbarán	object[82]|object[83]|person[85]	new[82]|new[83]|new[85]	Francisco_de_Zurbarán[85]	coref	15-25[120_85]	
```

it should be

```
12-16	954-962	Zurbarán	object[82]|object[83]|person[85]	new[82]|new[83]|new[85]	_|_|Francisco_de_Zurbarán[85]	coref	15-25[120_85]	
```

The problem is systematic and repeats for each line containing stacked annotations and an identity. Here is a corrected file.

[GUM_academic_art.tsv.zip](https://github.com/amir-zeldes/gum/files/7798301/GUM_academic_art.tsv.zip)

To set a project up in INCEpTION for importing the file, first go to the layer settings page in project settings and then click on the "import" button at the top of the layers list and import there there following layer config file (extract the JSON from the ZIP first).

[gum-coref-layers.json.zip](https://github.com/amir-zeldes/gum/files/7798306/gum-coref-layers.json.zip)

Note that it is not possible to manually configure INCEpTION for the current GUM TSV schema because the name "type" is used for a column but that is a reserved name and cannot be set via the GUI. It would be better to adjust the schema to use e.g. "value" or "kind" instead.

**Comment by fishfree** [comment]
@reckart Thank you very much for your sharing!

**Comment by amir-zeldes** [comment]
Hi everyone, sorry this took me a while to look at - I'm a little surprised, since I recall empty string values (i.e. existing but zero length) were represented as `*` in the past. I think in our current tool chain, including the SaltNPepper importer for WebAnno TSV, if we have a value like:

`_|_|Francisco_de_Zurbarán[85]`

It will infer that that token has two identical span, single-token annotations with the identity values "_". Only exactly one underscore in a column would mean 'empty'. This is because:

  * WebAnno TSV uses a format in which not specifying a span ID like `[85]` means "this annotation applies to a span encompassing only this token (which in edges is referred to using the token number only)
  * As soon as a line is non-identical to just "_", its values are split by `|`
  * The resulting values are non-empty

I'm not 100% sure what would happen to the tools if we tried

`||Francisco_de_Zurbarán[85]`

instead, that might work if they reject empty strings, but I'm pretty sure "_" will not work unless it is the only value. @reckart am I hallucinating this about `*` as a value or did something in the format change?

In any case, I'm not sure if it's worth dealing with this in GUM anymore, since we don't actually use WebAnno as a tool, just the format, and we may end up replacing it with just CoNLL-U in the future ([this](https://github.com/UniversalAnaphora/UniversalAnaphora/blob/main/documents/UA_CONLL_U_proposal_compact.md) is the current working proposal for NER, coref and Wikification).

**Comment by reckart** [comment]
* A column represents a feature of a given layer.
* A `_` indicates that there is no annotation of the layer that the feature the column represents belongs to.
* A `*` would indicate that there is an annotation of the layer type the columns belongs to, but the particular feature represented by the column is empty.
* If two annotations of the same type exists on a given token (row), then they are separated in each column by `|`.
* In this case, we have a layer with two features -> so two columns per this layer.
* So if we have two overlapping annotations on some token, we have two values in each of the columns separated by `|`

```
new[82]|new[83]|new[85]	_|_|Francisco_de_Zurbarán[85]
```

* So here we have three annotations here in two columns that both belong to the same layer. 

@amir-zeldes so I think your analysis is right. It should be actually

```
new[82]|new[83]|new[85]	*|*|Francisco_de_Zurbarán[85]
```

... because obviously there is still an annotation but the feature represented by the second column doesn't have a value.

**Comment by amir-zeldes** [comment]
OK, thanks for checking; TBH I find the version with just `Francisco_de_Zurbarán[85]` the easiest to understand and read: if we use the square brackets to indicate the span in question (which I wish was universal, even for single token spans), then there is no need to specify empty values for every other span mentioned on that line. It's the same with the major underscore: we just say `_` if no wikification is entered, and not `*|*|*`. If we need to load this back into webanno then of course we'll have to worry about compatibility, but since SNP and the build bots various scripts expect this format at the moment, I think we'll just leave it as is.
