### ISSUE TITLE
"in that"

### ISSUE THREAD

**Issue by nschneid** [amir-zeldes/gum#120]
This connective is now documented at https://universaldependencies.org/en/dep/fixed.html#pragmaticmiscellaneous-markers

There is one token in GUM, in the "cyclone" document

**Comment by amir-zeldes** [comment]
Hm, I don't love expanding the fixed list, but I suppose if we have 'so that' maybe we should have 'in that' as well. I never really understood why we don't just double-mark here, especially since you cand drop 'that':

  * I did it so the cookies would be yummy
  * I did it so that the cookies would be yummy

They seem like to separate words to me (both mark, sure, but why make it 'fixed'?)

**Comment by nschneid** [comment]
"in that" is definitely idiomatic, so at least as good a candidate for `fixed` as "so that".

I see your point about "so that" though. My priority right now is to get the data consistent, but I'd be open to reconsidering some of these down the road.

**Comment by amir-zeldes** [comment]
OK, I'll add 'in that' to the list for now and correct that tree.
