### ISSUE TITLE
"away from" suspicious deps

### ISSUE THREAD

**Issue by lgessler** [amir-zeldes/gum#136]
https://gucorpling.org/annis/#_q=ImF3YXkiIC4gImZyb20i&_c=R1VN&cl=5&cr=5&s=0&l=10

In "... away from Cara", we have `nmod(away, Cara)` which seems wrong--should be `obl`

**Comment by amir-zeldes** [comment]
Nice catch, I have no idea why the validator let this through! There are 108 ADV->nmod in GUM:

https://gucorpling.org/annis/#_q=dXBvcz0iQURWIiAtPmRlcCB0b2tfZnVuYz0ibm1vZCI&_c=R1VN&cl=5&cr=5&s=10&l=10

All of these are clearly wrong. I think I will just uniformly depedit them into obl and add to the GUM validator. Weird that this hasn't come up before.

**Comment by lgessler** [comment]
Wow that's a lot of affected lines! Are you sure it's fine to trust the xpos over the deprel like that? I guess I'd normally trust the xpos more...

**Comment by amir-zeldes** [comment]
I skimmed the ANNIS cases and it looked like simple errors. Mostly RB.? is also deprel advmod, so that seems pretty clear, and nmod/obl are both PP dependents, so really which one it should be in this context depends exclusively on the POS tag. Feel free to do a quick pass on the ANNIS link above and let me know if you notice a mistagging (it would have to be a noun mistagged (RB|JJ).* with an nmod dependent)
