### ISSUE TITLE
A couple of ccomps that should be csubj (extraposition)

### ISSUE THREAD

**Issue by nschneid** [amir-zeldes/gum#143]
https://universal.grew.fr/?custom=644d42f39f206

**Comment by amir-zeldes** [comment]
Are you sure these are wrong? The clause in question seems to be standing in for an object, represented by an expletive it. I don't think they are the subject - in the first example, the subject is "Carroll" and in the second the subject is "we". I think this sentence:

  * Carroll found it difficult to look directly at her

Is the extraposed object version of:

  * Carroll found looking directly at her difficult

Since that's heavy, we get an expletive object it  - but "to look at her directly" is what Carroll found difficult, not the thing doing the finding, right?

**Comment by nschneid** [comment]
You're right. I forgot ccomp could be involved in extraposition (it's usually csubj).
