### ISSUE TITLE
obj should be iobj

### ISSUE THREAD

**Issue by nschneid** [amir-zeldes/gum#146]
With pronouns: https://universal.grew.fr/?custom=644ebd584cb1a But in GUM this should be extended to all animate nouns.

Tricky case: "Thank God that..." (and similar) means that "thank" can license an iobj+ccomp. Do we want to say that "thank" objects should always be iobj, or treat this as an exceptional idiom?

**Comment by nschneid** [comment]
related to UniversalDependencies/UD_English-EWT#55

**Comment by nschneid** [comment]
Also a bit borderline: "believe" and "trust". But these can have an object + ccomp: "Trust me that it will happen." COCA: "He really believed me that I was going to do this for him."

**Comment by amir-zeldes** [comment]
> Thank God that

That is admittedly very marginal. We have no cases of thank+ccomp in GUM at all, and that's 200K tokens from very different genres... It's also not a typical ccomp since it's not the contents of the thanks, it's the reason (equiv. to "thank X *for* Y"). But if you want iobj here I guess I can live with it (incidentally, danken takes dative in German, suggesting there is some historical evidence it is somehow not a proper accusative object)

> Also a bit borderline: "believe" and "trust"

I would be more OK with these taking iobj (believe X that Y sounds quite normal, and it is the content of the belief, so it's a pretty canonical case IMO)

**Comment by nschneid** [comment]
OK.

- iobj in general for "believe" and "trust" (a source/authority)
- typically just obj for "thank", but with a Divine Exception of iobj for the construction "thank God/goodness/heavens/etc. (that...)"

**Comment by amir-zeldes** [comment]
> iobj in general for "believe" and "trust" (a source/authority)

Just implemented in GUM, thanks!

> a Divine Exception of iobj

😂
