### ISSUE TITLE
some errors involving nouns

### ISSUE THREAD

**Issue by nschneid** [amir-zeldes/gum#149]
GUM_fiction_veronique-1, "The Cost to Be Wise" - "Wise" is tagged as VERB for some reason. "Be" should have feats based on its upos (AUX) rather than xpos (NNP).

GUM_bio_marbles-18, "How To Avoid Talking To People You Don't Want To Talk To" - "Do" should have feats based on AUX rather than NNP

GUM_academic_huh-8, "?" after "Huh" has wrong xpos and feats

GUM_voyage_chatham-2, word 2: lemma should be the corrected spelling, "Chatham"

GUM_voyage_oakland-4, word 26: lemma should be the corrected spelling, "Hells"

GUM_whow_ballet-32, word 10: lemma should be the corrected spelling, "positioning"

**Comment by amir-zeldes** [comment]
Nice catches, unfortunately NNP upos mapping is non-trivial... Let's see what we can do about these:

> GUM_fiction_veronique-1, "The Cost to Be Wise" - "Wise" is tagged as VERB for some reason. "Be" should have feats based on its upos (AUX) rather than xpos (NNP).

This is triggered by having child TO leading to upos predicted to be VERB, which is usually right. I added a check to prevent this for nodes with a cop child. Additionally I guess we could catch more ADJ cases with a list. Let me try doing this with ADJ where f as JJ >= 5 and it's never attested as a non-JJ POS tag. Let's do ADV too for good measure.

> GUM_bio_marbles-18, "How To Avoid Talking To People You Don't Want To Talk To" - "Do" should have feats based on AUX rather than NNP

This is trickier since we can't know whether "Do" is finite by looking at VV vs. VVP (since xpos is quashed by NNP). I'll just hardwire this one.

> GUM_academic_huh-8, "?" after "Huh" has wrong xpos and feats

This is a source gold tagging error, will fix

> GUM_voyage_chatham-2, word 2: lemma should be the corrected spelling, "Chatham"

Right, another error, will fix

> GUM_voyage_oakland-4, word 26: lemma should be the corrected spelling, "Hells"

Not sure what to do about this one. Wikipedia cites the Hells Angels as saying:

  *  "According to the Hells Angels' website, they are aware that there is an apostrophe missing in "Hell's", but "... it is you who miss it. We don't".

According to this, I guess it IS a possessive, so the two tokens should be retained. But I guess token 2 should be xpos=POS, case, etc., but `CorrectForm=s`? And still lemma "'s"? Does that sound right??

> GUM_whow_ballet-32, word 10: lemma should be the corrected spelling, "positioning"

Thanks!

**Comment by nschneid** [comment]
Hell(')s Angels: If you want to say the "s" correctly denotes the possessive despite lacking an apostrophe then I think it should be flagged somehow (`Style=Rare`?) to avoid giving the wrong impression about how possessives are supposed to be spelled. I'd be fine with saying that "Hells" is a lemma that incorporates possessive meaning, like "its", as long as it's consistent in the document.

**Comment by amir-zeldes** [comment]
Mm, I think syntactically we are still dealing with the s possessive, it's just that in this name, they prefer to spell it without the apostrophe. So I guess the tree is totally normal, but still CorrectForm is `s` in this particular context and it's technically a Typo.

**Comment by nschneid** [comment]
It could be considered "correct" or "incorrect" depending on the authority, but I would expect consistency between Typo and CorrectForm: with Typo=Yes the CorrectForm should differ from the surface string.

**Comment by amir-zeldes** [comment]
Right, I went with CorrectForm=s and Typo=Yes

**Comment by nschneid** [comment]
Oh OK. The group is actually mentioned twice in GUM, once with the apostrophe and once without. So where it's spelled "Hells Angels" the "s" should be split off as a correctly spelled clitic?

**Comment by amir-zeldes** [comment]
ooh, good point! From a generic NLP perspective it's unexpected, but I see your argument for consistency. What do you think?

**Comment by nschneid** [comment]
I would expect "Hell(')s" to have the same tokenization whether the apostrophe is "added" or not.
