### ISSUE TITLE
iobj false positives

### ISSUE THREAD

**Issue by nschneid** [amir-zeldes/gum#150]
https://universal.grew.fr/?custom=644ec19a14f5a (one is a wrong lemma)

**Comment by amir-zeldes** [comment]
"contact" and "entitle" are wrong, but the others I think are right.

**Comment by amir-zeldes** [comment]
Weirdly for entitle, since it's passive, and the subject is the canonical iobject, we get object + passive subject:

  * The protection which/obj he/nsubj:pass is entitled

Without modern "entitled *to*" it becomes a passivization of something like:

  * The law entitles him/iobj the protection/obj

So I guess nsubj:pass + obj is actually correct here!

**Comment by nschneid** [comment]
I guess I didn't read the "entitled" sentence carefully—I would say "the protection **to** which he is entitled". Without "to" it seems like an creative extension of the pattern seen with "owed".

Why iobj for "excuse me"? *He excused me that I forgot the deadline

**Comment by amir-zeldes** [comment]
> the protection to which he is entitled

Yeah, I would say it that way too, but this is a quote from a 19th century proclamation, so I suspect in that speaker's grammar it actually *was* ditransitive (at least taking the sentence at face value, that's how I read the intended syntax)

> Why iobj for "excuse me"? 

I thought it's possible to say things like "excuse me the intrusion"?

**Comment by nschneid** [comment]
With "pardon" yes: "pardon me the interruption" being the exemplar. I don't think I have it for "excuse".

**Comment by amir-zeldes** [comment]
Intrusion and interruption are easy to find:

  * [excuse me the intrusion](https://www.songtradr.com/songs/nicholas-chim/caterwauling)
  * [excuse me the interrupion](https://books.google.com/books?id=1He3EAAAQBAJ&pg=PT367&lpg=PT367&dq=%22excuse+me+the+interruption%22&source=bl&ots=DqGO6qj07x&sig=ACfU3U0ZONX4ZQCcpoNCjB8c6wmneUxiow&hl=en&sa=X&ved=2ahUKEwjer6_53tL-AhUMEVkFHRCWDbsQ6AF6BAgWEAM#v=onepage&q=excuse%20me%20the%20interruption&f=false)

Other examples can be found in encow:

  * please excuse me the inaccuracy of the term
  * I keep wondering , bloody hell , maybe I should get on the case , be more sensible , and at least say Hello . But I excuse myself the responsibility because he 's always animatedly talking with them

**Comment by nschneid** [comment]
Sounds a bit nonnative to me. But I see it does occur! This is the tricky thing about defining a label based on the verb's compatibility with a potentially infrequent alternative (where there is likely to be interspeaker variation). Which is why I'd be happy in UDv3 to demote the indirect/direct distinction to a subtype—that it's an object is clearer than whether it's indirect.

**Comment by amir-zeldes** [comment]
not necessarily objecting, but then we'd need to drop the 'no two objects' constraint
