### ISSUE TITLE
Subjects with erroneous case

### ISSUE THREAD

**Issue by nschneid** [amir-zeldes/gum#159]
[7 results](https://universal.grew.fr/?custom=64e7fd1a22e84) (I think the vlog_london one is correct)

Some of these are prepositional passives, but the prevailing approach (also in EWT) is to attach the stranded preposition directly as `obl`: https://universal.grew.fr/?custom=64e7fc694222d

**Comment by amir-zeldes** [comment]
Three of those are just errors, will fix. For the prepositional passives I disagree - attaching the preposition as `obl` incorrectly suggests that there is an additional participant. I think representing the correct number of dependents of a verb is a very high priority, so I would like to leave those cases as they are.

**Comment by nschneid** [comment]
If the prepositional passive is a non-relative adnominal clause, the stranded preposition is necessarily `obl`:

- children taken care **of** by a professional staff

This is similar to the treatment of preposition stranding in zero-relatives (in basic UD; the preposition would attach as `case` in the enhanced graph).

I guess the question is what to do when the clause has an overt subject in basic UD:

- The children will be taken care **of** by a professional staff
- New Delhi can always be counted **on**

`case(children,of)` doesn't feel quite right to me because I don't think the preposition belongs in the subject—the subject is not a PP (*Of the children will be taken care by a professional staff; *On New Delhi can always be counted). In transformational terms, the preposition goes with the noun only in deep structure. I would lean toward again treating it as a `case` dependency only in the enhanced layer.

**Comment by dan-zeman** [comment]
Alternatively, one could say that the passive subject is actually not a subject (but oblique). It would be somewhat analogous to languages like Czech or German where passivization of clauses with non-accusative arguments will not promote those arguments to subjects:

* _O děti bude dobře postaráno_ lit. "Of children will-be well taken-care-of" (_O děti_ is `obl:arg`)
* _Je počítáno s ubytováním_ lit. "Is counted with accommodation" (_s ubytováním_ is `obl:arg`)

On the other hand, English is different in marking person+number agreement with the prepositional "subject", while in Czech, the predicate switches to the default neuter singular form.

**Comment by amir-zeldes** [comment]
The English situation is indeed different, since, as Dan alluded to, we say "The children are being taken care of", unlike German where it would be something like "it is being taken care of the children". As such, the English passived obliques are seen as `nsubj:pass` in UD. I feel quite strongly that there should not be a separate `obl` edge to the stranded preposition - that would imply that the verb simultaneously has an oblique dependent AND a subject, but that is not correct - both tokens are involved in encoding the function of a single participant, where the case marker only indicates the function of the argument in the equivalent active sentence. As a result, I think it is appropriate to keep labeling it as `case` and attach it to the passivized subject argument, not the verb.

**Comment by dan-zeman** [comment]
I tend to agree with Amir that the preposition should be attached to _children_ (and, yes, perhaps it can be then labeled `nsubj:pass`). This seems to me slightly less odd than to make the preposition look like a separate argument. But it is odd anyway, not only because subjects are not supposed to have prepositions but also because the case form of the subject is inappropriate for a preposition (_they_ are taken care of; but one takes care of _them_).

It just occurs to me that if the preposition were to be attached separately to the verb, the relation could be `dislocated`, which is one of the options we have when a core argument is present doubly. (And as a bonus "dislocated" and "stranded" sound like similar meanings to me :-).)

**Comment by nschneid** [comment]
English has (rare) PP subjects ("Behind the garage is full, why don't you put it in the basement?"), but there the elements of the PP are in their canonical order and the object of the preposition would have accusative case as expected.

I think this goes back to the deeper question of what "is" surface structure vs. deeper (enhanced) structure according to UD theory. We saw this with the disagreement about how `case` dependents should work in the enhanced graph with relative clause stranding (are they associated with the relativizer, or the antecedent, or removed entirely?).

Thinking in terms of licensing, the verb regardless of voice licenses a preposition, which would normally be part of an oblique, but the passive construction licenses the subject and "steals" it from the oblique.

Since this construction tends to go with idiomatic verb+preposition combinations, maybe we should be thinking along the lines of `compound:prt`?

**Comment by dan-zeman** [comment]
> Since this construction tends to go with idiomatic verb+preposition combinations, maybe we should be thinking along the lines of `compound:prt`?

I don't think it would make the analysis less odd. The behavior is different. For normal `compound:prt`, the word order is _you can look <b>it</b> up_ (not sure if this order is mandatory, but it is at least possible and I take it as default). But you say _I count on <b>it</b>_, not _I count <b>it</b> on_. And you also don't say _I take care <b>it</b> of_ – I don't even see where the preposition would be attached as `compound:prt`: to _take_, or to _care_?

**Comment by amir-zeldes** [comment]
Agree with Dan. For me `compound:prt` suggest a lexical entry for a phrasal verb "take of" with a possibly distinct meaning. As a type of compound, phrasal verbs are distinct from their base verb, but this would not be the case here. It's just a productive argument configuration transformation, not compounding IMO. I'm really fine with leaving it as `case`, parallel to what it does in the active version.

**Comment by nschneid** [comment]
I see your point—the idiom is "take care of", so to be consistent we'd have to make the whole thing a compound only in the prepositional passive construction.

I'm definitely not advocating for treating prepositional verbs as `compound:prt` in active voice. So it would be sort of a hack to do so in the prepositional passive.

It still feels wrong to put `case` under `nsubj` since the preposition is not and cannot be paraphrased as a part of the subject. Let's see what the rest of the group thinks.
