### ISSUE TITLE
Syntax for "you guys"

### ISSUE THREAD

**Issue by lgessler** [amir-zeldes/gum#71]
Attested analyses:

* EWT
  * you <=dep= guys 
* GUM: 
  * you <=det= guys
  * you <=compound= guys
  * you =appos=> guys
  * you =compound=> guys

**Comment by lgessler** [comment]
Still mulling it over but consider the following:

(1) So all you went to the party?
(2) So all of you went to the party?
(3) So all you guys went to the party?
(4) So all of you guys went to the party?

(1) is pretty bad for me, at least a `?`. If that's the case, then I think this is evidence against any *you => guys* analysis since you'd need to explain why (3) is OK when (1) isn't when the only difference is that *you* has a modifier in (3) and doesn't in (1)

**Comment by lgessler** [comment]
@esmanning and @nschneider think `you =appos=> guys` is the right analysis, guided by the intuition that `guys` is a grammatical number marker like in `you two`, `you all`. Some other evidence to consider:

(5) * So all guys went to the party?
(6) * The you guys went to the party?
(7) * Good you guys went to the party
(8) You good guys went to the party **(OK but grammatically distinct, the `you =appos=> guys` which exists alongside whatever `you guys` normally is)**
(9) Where are you guys going?
(10) Where are you going?
(11) *Where are guys going?

**Comment by nschneid** [comment]
I think `dep` or maybe `nmod`, not `appos`. One reason is that they're not (in general) interchangeable:

(12) *Where are guys you going?

**Comment by nschneid** [comment]
Or hey, what about calling it an MWE with `fixed`? Then the head is "you" as it is the first word, but it's basically claiming to be a separate pronoun from plain "you".

**Comment by amir-zeldes** [comment]
I'd be opposed to `nmod` since I like its restriction to case marked environments in English (where we have `nmod:xyz` for various non-prepositional cases). Additionally, nmod doesn't really capture the fact that "you guys" fulfills only a single syntactic role in the sentence and generates only one joint referring expression (so more similar to `fixed` or `appos`). 

So I can see the appeal of both appos and fixed, but there are some problems with this:

  * As Nathan mentioned, it's not reversible (*guys you), so `appos` is so-so
  * If it's fixed, what do we do about:
    * Random expansions like "**you pilots** all think you're great" (hard to have a closed list, needed for `fixed`)
    * Multi word expansions like "**you Nobel Prize laureates** are all the same!"

If we accept that they are all the same construction (which I think they are underlyingly, even if 'you guys' is much more frequent), then the last one seems especially problematic, since `fixed` would require us to disregard the internal structure of the modifier "Nobel Prize".

For this reason I'd say we should reject `fixed`, but I'm on the fence between `compound` (in either direction), `dep` or just living with a non-reversible `appos` in this case. Let me know what you think, adding @sebschu and @manning in case you have thoughts on this and/or know the history of the EWT annotations.

**Comment by nschneid** [comment]
> If we accept that they are all the same construction (which I think they are underlyingly, even if 'you guys' is much more frequent)

I'm not sure they are the same construction synchronically—arguably "you guys" has become grammaticalized as a plural form of "you" (reinforced by the observation that "guys" is gender-neutral for many). Whereas the others elaborate on the category of the addressee to specify who is included in the set.

But in any case we need a policy for the "you pilots" construction. Compounding doesn't usually involve pronouns and unlike typical appositives it's not reversible. Maybe [`flat`](https://universaldependencies.org/u/dep/flat.html)—cf. "French actor Ulliel", where a descriptive category and a specific entity reference in that category are also paired (but this is not uncontentious: UniversalDependencies/docs/issues/503). Or `dep` to signal that we really don't have a good label for it.

**Comment by nschneid** [comment]
Reflecting on this more, I think we have a few different NP constructions with a similar function (call it "entity-equative"), and the `appos` guidelines as written with the reversibility test are specific to one of these constructions, whereas the others are awkwardly placed in `flat`. Might be better to broaden the definition of `appos`.

**Comment by amir-zeldes** [comment]
I'm OK with appos or dep, but would vote against flat, since it's not really 'no syntax', and would create the same problem for the Nobel laureates (flat requires only LTR fountain-style deps with first token as head). And I think although "you guys" is definitely entrenched, there's nothing overtly different about "you pilots" as far as I can tell... or in any case, if we had a good solution for the other cases, I see no reason not to apply it to "you guys" too.

**Comment by sebschu** [comment]
I just went back to the notes from the annotations before my time and they decided back then to make it `det(guys, you)` since it has a similar distribution as `det(guys, those)` and other determiners. 

I'm not sure I agree with it (my gut reaction is that it is very strange to call `you` a determiner) but I'm putting it out here as another option to consider :)

**Comment by nschneid** [comment]
Hmm...from a functional perspective it seems odd that the nsubj of _you guys are late_ and _you are late_ would be different (considering that they have the same meaning). True, with "those" or "both" (_those/both (cats) are mine_) the meaning-in-context would be the same. But "those" and "both" used as pronouns assume a referent has been established previously, whereas "you" normally does not require elaboration, so it feels weird to call it a determiner when there is a clarifying descriptor.

Maybe another way to say this is that "those" and "both" could have grammaticalized from determiner to pronoun, whereas this direction of extension seems implausible for "you".

Probably worth a look in CGEL...I do recall discussing the determinative use of "said" (*said parties agreed to the terms of the contract*) with one of Geoff Pullum's students, so there might be a case for determinative "you" as well.

**Comment by nschneid** [comment]
> would vote against flat, since it's not really 'no syntax'

@amir-zeldes TBC you also dislike `flat` for "French actor Ulliel" (the relation between "actor" and "Ulliel")? Seems to me that is a syntactic construction as well.

**Comment by esmanning** [comment]
Just saw this but I want to clarify that I never said it was `appos` and don't think it is! I'm probably too rusty on UD to contribute much here beyond that.

**Comment by amir-zeldes** [comment]
@nschneid no... well, yes, I do dislike it, but I wasn't intending to open that can of worms. I'm aware of the motivation for this guidelines by analogy to titles like "Mr.", and in most cases it kind of works (makes it clear it's a single entity term, not an apposition), but there are corner cases that speak against it, much like "you prize winners". The steps to produce the paradox go like this:

  * `flat` is supposed to have no head, so arbitrarily, we pick the left most token: "actor Ulliel" is actor -> Ulliel
  * If we have "French", that is definitely amod, so now we are forced to do "French" <-amod- "actor". We feel good about this, since indeed French modifies actor, but we're forgetting that we promised "actor Ulliel" has no structure, so really "French" modifies the whole thing
  * So far so good, but what happens if there is a right side modifier too? Say: "French Winner of the Nobel Prize Ulliel". At this point, we have "winner" with all of its syntactic modifiers attached as normal and `flat` just sort of continues to the right...
  * Worse still, if Ulliel has modifiers like a possessive 's, it's even worse, since by guidelines, `flat` can't have children. So in "French Winner of the Nobel Prize Ulliel's house", we are forced to have winner -case-> 's...

But back to my 'no', no, I don't have plans to tackle this issue ATM, especially since it is non-trivial to convert automatically and I don't have an alternative that also works for "Ms." & co. that I'm happy with... makes me miss SD `nn` :|

**Comment by nschneid** [comment]
Or even: "French queen consort and literary patron Eleanor of Aquitaine"—surely we don't want this to end up with "of Aquitaine" attaching to "queen"! I would say this construction is [descriptive nominal phrase] [proper name], where the proper name is the head. I think the descriptive phrase cannot be indefinite, though "the" is optional.

Now I'm noticing something weird regarding reversibility and determiners:

- French actor Ulliel said... / Ulliel, *(the) French actor, said...
- French queen consort and literary patron Eleanor of Aquitaine said... / Eleanor of Aquitaine, ?(the) French queen consort and literary patron, said...

It seems less objectionable to omit the determiner in the second case. I wonder if there are subtle effects on determiner use that the `appos` test of reversibility is glossing over.

More broadly, I would guess that English has a family of related constructions that I will put under the umbrella of "nominal-nominal juxtaposition" (excluding canonical `nmod` where e.g. the modifier has case marking):

- "nominal-nominal juxtaposition"
  1. `compound` with two nouns, second one is typically the head and not a proper name
  2. expanded 2nd person: "you" (head) + bare nominal phrase
  3. honorific titles/appellations before a name: e.g. "Mr." (dependent) + "John Smith" (head)
  4. descriptive (possibly bare) nominal phrase before a name: e.g. "French actor" (dependent) + "Ulliel" (head)
  5. `appos` with two full NPs, first one is the head 
  6. truly headless (`flat`) combinations which are arranged in a templatic linear order: "John Smith", maybe "July 4"

I think in Stanford Dependencies `appos` matches (v) and `nn` would cover all the other cases.

**Comment by nschneid** [comment]
FWIW here's CGEL p. 539:

![image](https://user-images.githubusercontent.com/985263/97501888-779c3e00-1948-11eb-94fb-015b9db0154b.png)

So indeed they would classify "you" as determinative in "you pilots". I couldn't find a mention of "you guys" specifically.

That said I strongly suspect `det` would be counterintuitive for UD annotators here.

**Comment by nschneid** [comment]
Updated my list [above](#issuecomment-718231522) to add item (vii) and mention "2003 agreement" under (iv).

**Comment by nschneid** [comment]
The `amod` dependent POSes seen in [this query](http://match.grew.fr/?corpus=UD_English-EWT@2.6&custom=5fa294037a33b&clustering=DEP.upos) (from UD_English-EWT#102, which is focused on VERB) are fascinating.

**Comment by amir-zeldes** [comment]
RE vii, I don't think "July 4" is headless - I think the head is 4. In iv. I think "2003 agreement" is a compound (with the semantics "agreement happening in 2003", but still a compound)

**Comment by nschneid** [comment]
The reason I listed "2003 agreement" as worthy of discussion is that "2003" is a named entity of sorts, and the form is numeric. So annotators might be tempted to call it `nummod` or something. But the fact that it requires an article (unlike "French actor Ulliel") makes it more compound-like I suppose.

**Comment by nschneid** [comment]
> RE vii, I don't think "July 4" is headless - I think the head is 4

Open for debate. Semantically I agree with you, but syntactically you can't simply omit "July"; you need a determiner if referring to "the 4th". And there are various stylistic conventions for dates ("July 4", "4 July" and so forth) which suggest that these are special constructions for expressing dates.

**Comment by amir-zeldes** [comment]
The last point may come down to whether or not you assume special constructions for written English (e.g. is `$ 500` a special thing, or can we read it as `five-hundred dollars`, and treat the dollar symbol as a head).

If you say `July 4th` I think it has the same headedness as `the 4th of July`, where `4th` is clearly the head. In `July 4th` in particular, our analysis in GUM has been to see this as a kind of compound: there are many kinds of "4th"s (any 4th day of any month), and "July 4th" is a particular subtype of those (so a standard determinative compound).

The absence of 'th' doesn't do much to change this IMO. You say we can't omit '4', but if we accept written English I'm not so sure about that. Imagine a list of dates with months as headings:

```
July
===
1 - go to the pool
4 - fireworks
```

In this case it seems clear that July is droppable for the '4' entry, but we definitely can't drop 4 (otherwise we wouldn't know what day is being discussed). All of which makes me see '4' as the head (and it's also more consistent across different date constructions that way).

**Comment by nschneid** [comment]
1) July is droppable at the semantic level, but to refer to the date you have to say "the fourth", not simply "fourth":
   - I am the fourth of the students in my year
   - I am fourth in my year.
   - The date is the fourth of July.
   - *The date is fourth in July. (intended meaning: fourth day of July)

2) How would you analyze "4 July" pronounced "four July"?

**Comment by amir-zeldes** [comment]
1. The fact that dropping a different specifier requires introducing another determiner is not necessarily evidence, consider "your brother", where you can't just say "brother", but have to replace "your" e.g. with "the". The fact that "July 4th" and "the 4th" are in alternation suggest that either specifier can be used to determine "which fourth" it is and license the NP. Aside from that I'm not sure what the infelicity of "in" is showing - I would think the syntax of "the fourth of July" is unambiguous (nmod(fourth,july))

2. In my own personal English I don't really feel comfortable pronouncing that "four July", so it's hard for me to answer it using intuition. I would read "4 July" as "July fourth" or "fourth of July", similarly to how I read "$ 500" in reverse sequence ("five-hundred dollars"). So I feel more like it's a written construction, and I still feel like 4 is the head and July is the expansion. I guess if you take it literally as "4 July" then it's a little like "4 tomorrow" (i.e. 16:00) or "the 12th next month", which would be `nmod:tmod`.

**Comment by nschneid** [comment]
Re: determiners—are you arguing that "July" is basically a determiner in "July fourth"? What about in "July the fourth"—is it essentially a predeterminer there? Cf. "James I" pronounced "James the first".

(I'm actually wondering if in earlier forms of English there may have been a more productive ordinal construction with the form "HEAD the ORDINAL"....also thinking of non-ordinal names like "Robert the Bruce" and "William the Conqueror".)

**Comment by nschneid** [comment]
^ as in "Book the First" (e.g. in _A Tale of Two Cities_ and [this](https://www.google.com/books/edition/Notes_to_Blackstone_s_Commentaries/IEA0AAAAIAAJ?hl=en&gbpv=1&dq=%22book%20the%20first%22&pg=PA26&printsec=frontcover&bsq=%22book%20the%20first%22))

**Comment by amir-zeldes** [comment]
No, I'm not saying it's a determiner, just that sometimes when you omit something you have to substitute it with something else. Just because you can't drop "July" in "July 4" (and actually in my list example I did drop it!) wouldn't necessarily mean it is a headless construction. 

As for the others, I think it's maybe expedient to treat "James the first" as `appos`, though the construction is probably a little distinct from normal apposition under the hood. The alternative is LTR James -det-> the, and James -amod-> first, which maybe has some historical justification in Norman French influence in the middle ages, but synchronically looks a bit avant-garde.

**Comment by nschneid** [comment]
In CGEL, the closest I can find to a discussion of the internal syntax of dates is on p. 416:

![image](https://user-images.githubusercontent.com/985263/98446697-43b1dd00-20ed-11eb-98f7-3c956c45e8f2.png)

("Fused head" apparently means what would normally be a modifier, such as an ordinal adjective, standing for the whole nominal as in "the fourth".)

**Comment by amir-zeldes** [comment]
I think there's nothing unusual about "the fourth" vs. "the fourth of X", they should all be headed by the ordinal, which is basically a nominalized adjective. BTW we just had "you birds" in a new GUM document, referring to some women, and we treated it like "you guys".

Another related construction which is treated differently is "you all" (not just "y'all", but also in stressed "you ALL wanted to do this"). Here EWT has you -det-> all in all senses (including "y'all"), and we've reproduced that analysis in GUM, though I'm not certain it's right, since you can separate it as a floating quantifier (e.g. "you should all be ashamed of yourselves")

**Comment by nschneid** [comment]
See also UniversalDependencies/docs#478 for miscellaneous relations inside an NP

**Comment by nschneid** [comment]
Back to "July 4/fourth": if `compound(4, July)` is under consideration, is it relevant that dates don't follow the Compound Stress Rule? (see UniversalDependencies/docs#675)

Pronunciation of a monosyllabic month: "it will happen on june FOURTH", not "it will happen on JUNE fourth" (except with contrastive stress). Contrast "JUNE bug", which is `compound`.

Not actually sure I like this test, because a productive combination like "a June party" should also be `compound`, I think, yet the primary stress is on the head noun.

**Comment by amir-zeldes** [comment]
> is it relevant that dates don't follow the Compound Stress Rule?

No, I think for N+N the compound analysis is selected regardless of stress. As I commented [here](https://github.com/UniversalDependencies/docs/issues/756#issuecomment-761829326), CSR represents a historical facts about compounds as they were inherited from older Germanic grammar, but this system is falling apart in contemporary English IMO. 

For N+N there is no good alternative (unlike A+N, which could be `amod`), so compound is the best option. I don't really feel strongly about "July 4" being `compound`, but I do feel strongly that "4" is the head. If you think it's better to call it `nmod:tmod` then for me that would be an option as well. The word order and semantics just made `compound` a plausible contender, and maybe the fact that this used to be `nn` in Stanford Dependencies, and the default conversion for nn was compound.

**Comment by nschneid** [comment]
I like `nmod:tmod` better actually. It doesn't feel like a "normal" compound to me and the `:tmod` suffix nicely says "this is temporal so the usual bets about determiners/case are off".

**Comment by amir-zeldes** [comment]
Not that I was unhappy with compound, but I could also live with nmod:tmod, so if that gets us to consensus, that's fine. However GUM7 is nearly ready for release, so I won't mess with this until next time, and ideally only once we're doing EWT too, since I wouldn't want to have to change to yet another analysis that EWT folks agree to.
