### ISSUE TITLE
Suspicious nmod:npmod annotations

### ISSUE THREAD

**Issue by nschneid** [amir-zeldes/gum#82]
Here are 50 `nmod:npmod`s worth reviewing. Maybe the recipe ingredient ones are OK, but some of these are clearly errors.

http://match.grew.fr/?corpus=UD_English-GUM@2.7&custom=6032be56514f3

Some of the `obl:npmod` instances look like errors too.

**Comment by amir-zeldes** [comment]
Thanks for reporting - for clarification, do you mean these should be `obl:npmod`, or something else entirely?

**Comment by nschneid** [comment]
Some of them look totally wrong

**Comment by amir-zeldes** [comment]
OK, so for the ones that are some kind of `*:npmod`, I guess I could use some clarity on which ones should be obl when the parent is neither a verb nor a noun: for predicative cases it's clear to me that it should be obl. For predicative adjectives for example, this is what we do regularly, but for nouns, it would really depend on whether or not they're predicative. For example, I would disagree with the second hit here, since the noun is predicative IMO:

http://match.grew.fr/?corpus=UD_English-EWT@2.7&custom=603404015b9e3

Looking at the cases in your search, I think I see three categories:

## Should maybe be obl:npmod
  * wheezing all the way home
  * I hope he’s there the whole way
  * First of all because it was beautiful

## Fine?
  * video ... all the way from the launch pad, too
  * of order a micron in size
  * inside the Palacio del Gobierno left of the main entrance
  * 1 cup quinoa etc. (there's a bunch of these, and I think it's prob. the best analysis)
  *  the chilly air 2,360 meters up
  * Fan Expo Canada **(not sure about this one, but I think it's not exactly `flat`)**; similarly "Vrije Universiteit Amsterdam"
  * equal parts soil (similarly "equal parts maple sugar or rice syrup")
  * 180 o C / 350 o F
  *  a member of Scientology all his life

## Messed up (not npmod)
  * someone who is in charge of the Britney Spears story of the week — the entertainment stories
  * We’ll attack People Magazine’s coverage of Britney as much as Britney
  * 24 hour comedy news cycle that exists on all the late night talk shows
  * Cancun: 250 MXN, Mexico City: USD 25 **(should this be `dep`? Better ideas?)**
  * other than eating **(suggestions?)**
  * so much beauty all around the island
  * Danish: [ʌtˢo ˈjɛsb̥ɐsn̩] **(this isn't totally implausible - I could see `dep` too, but if you have a better idea...)**; similarly "Greek: Αθήνα"
  * 311 cubic meters
  * around ten well preserved underwater shipwrecks

I would appreciate input on the boldface cases above. I can easily correct the trivial messed up ones, and I think the obl-group cases should probably be obl:npmod indeed.

**Comment by nschneid** [comment]
I'd probably use `fixed` for "other than", similar to "rather than", though EWT tends to treat "other" as ADJ

Re: "Cancun:", "Danish:" etc.—I guess `list` and `appos` per https://universaldependencies.org/u/dep/list.html

**Comment by amir-zeldes** [comment]
Fixed in dev, will propagate on release.
