### ISSUE TITLE
ratchet not tagged correctly

### ISSUE THREAD

**Issue by annmfin** [amir-zeldes/gum#85]
sentence | start | end | term_id | token_id | token | lemma | upos | xpos | feats | head_token_id | dep_rel | deps | misc
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

Basically, we do not give a fuck we gonna talk about shit what now, but we go keep it ratchet. | 383 | 389 | 98 | 22 | ratchet | ratchet | NOUN | NN | Number=Sing
-- | -- | -- | -- | -- | -- | -- | -- | -- | --

Here, ratchet is tagged as a noun but is actually used as an adjective. Is there a way to update tagging for slang terms? Thanks very much!

**Comment by amir-zeldes** [comment]
Hi @annmfin - I'm a little confused: the sentence you have above does not seem to appear in the corpus at all. The word "ratchet" also doesn't appear anywhere in GUM. Where is this data from and what would you like to happen with it?

**Comment by annmfin** [comment]
Hi @amir-zeldes. Thanks for the follow up. I apologize for the lack of clarity in my question. I misunderstood the purpose of the correction submissions page as a place to identify incorrect tags from texts external to the corpus. This is from a podcast corpus I am tagging using a GUM trained model in R, not a text from the GUM corpus itself. If we identify incorrect tags such as in this example, is it safe to assume that the only way to correct them is by hand?

**Comment by amir-zeldes** [comment]
No worries, that's fine - we are making a push to include more spoken data in GUM, but the corpus itself can't directly influence how out-of-vocabulary items (ones not attested in the corpus) are tagged by an external tool. 

If you're seeing some conspicuously bad performance you can try to contact the people who made the tagger you're using, but in itself it's not unusual for a specific word to be tagged incorrectly, since no tool is perfect. If the tagger in question uses a lexicon, then this word could be added explicitly to it, but otherwise, aside from general improvements to the tagger, the only way to "teach it" this and other words from this register would be to feed it more training data on top of GUM.

**Comment by annmfin** [comment]
Thanks so much @amir-zeldes. The podcast dataset I am using is available from [Spotify](https://podcastsdataset.byspotify.com/) via a licensing agreement - it may be worth looking into for GUM spoken data.

**Comment by amir-zeldes** [comment]
Thanks for suggesting it - we add new genres to GUM every three years, and we have two more to go with the current ones, but after that we'll certainly consider it. The current genres we're expanding do include face-to-face conversations, political speeches and YouTube vlogs, so the proportion of spoken data in the corpus is fortunately rising!
