### ISSUE TITLE
Wikipedia version for identifiers

### ISSUE THREAD

**Issue by antonyscerri** [amir-zeldes/gum#97]
Hi

Could you comment on which version (if you aren't just working against the live site) of Wikipedia dump you are using for the wikification identifiers? I've looked through the WikiGUM paper, GUM website and this repo but I couldn't find any statement with such information. 

Would you be able to confirm that the identifiers in this GUM corpus are those introduced in the WikiGUM paper, as there was no explicit link to the WikiGUM corpora and i just wanted to be sure. Do you have any eval scripts that you used for measuring performance like those used in the WikiGUM paper?

Thanks

Tony

**Comment by amir-zeldes** [comment]
Hi Tony, no, we don't have the identifiers sadly, it is as you suspected - because GUM is annotated by a large and constantly changing team of students, and Wikification is just one of a very large set of annotations, it is fastest to teach them to use the normal live Wikipedia website, which everyone is already familiar with.

That said, I think it would be great to include WikiData identifiers as well, and I think for most identifiers this wouldn't be difficult. @jl908069 , if you have time sometime maybe you could look into running a Wikipedia URL to WikiData identifier mapping script to include such IDs in GUM? I think there are numerous libraries for this, here is one: https://pypi.org/project/wikimapper/

With the eval scripts I'm not sure what you mean exactly, do you mean just for scoring system outputs? We simply used exact match P/R/F1 for that (exact token span match and Wikipedia title string), there was nothing fancy or unusual.

**Comment by antonyscerri** [comment]
Hi

Thanks for responding. In this instance I wasn't asking about wikidata identifier but the page titles (and whether you used a snapshot for consistency), but your answers addressed both :) For eval that's a straightforward match then, that's fine.

As for wikidata identifiers, yes there are mappings (and you can go between the two easily enough) something i've done on a few projects. If the annotators could capture it going forward they can use the "Wikidata item" nav link on the left side of the page to get the current identifier (of course these can change over time). The bigger issue is still around stability, with pages coming and going or changing titles, or being redirected over time. It might be interesting to review each wiki page referenced (and when it was added to the corpus) and look at the page history from that point to ensure its still there and whether the contents may have had significant edits which might have changed an opinion regarding any ambiguity.

Thanks again

Tony

**Comment by amir-zeldes** [comment]
Yes, I see what you mean. Wikification was only added to GUM starting last winter (to freshly collected data, and retroactively to the entire pre-existing corpus), so probably almost all of the identifiers are still valid and un-redirected, but that will surely change. Moving forward, each document's `dateCollected` metadatum is a close indication of when Wikification was done (probably about 8 weeks after that date). 

@jl908069 if we add a script to link to WikiData IDs, we could timestamp the result and make a table like this:

| Wikipedia   | Wikidata | DateVerified |
|-------------|----------|--------------|
| Santa_Claus | Q315796  | 2021-11-12   |

Then we could set up the GUM build bot to warn for changed Wikipedia titles and update those in the table and corpus.

**Comment by amir-zeldes** [comment]
This is now addressed in V8.0.0, which includes the Wikidata identifier mapping with a time-stamp for the most recent verification of the Wikipedia and Wikidata identifiers. As of V8.0.0 release, all identifier are valid and included in Wikipedia (timestamp: 2022-01-19). Detailed output here:

https://github.com/amir-zeldes/gum/blob/master/coref/wiki_map.tab
