### ISSUE TITLE
Missing entities

### ISSUE THREAD

**Issue by antonyscerri** [amir-zeldes/gum#98]
Hi

I'm not sure of the completeness of the released data with respect to inclusion of entities. However reviewing results the following file, which i believe contains the entities:

* coref/ontogum/tsv/GUM_news_iodine.tsv

Appears to be missing a number of entities for phrases like "United States" and "European". Also it has the word "foods" tagged pointing to "Food" but this seemed like it was outside the expected set of "Named" entities that were being targeted.

Tony

**Comment by amir-zeldes** [comment]
No, those entities should not be in that file - you are looking at the coref/ontogum/ directory, which contains a version of the corpus following the OntoNotes coreference annotation scheme, which includes only non-singleton (=co-referring) mentions. For more details on how OntoGUM is built, please see this paper:

https://aclanthology.org/2021.crac-1.15/

Because "United States" only appears once in that document, it is removed in the ontogum/ directories. However you can see that it is indeed annotated as expected in the regular GUM files:

  * WebAnno tsv: https://github.com/amir-zeldes/gum/blob/master/coref/gum/tsv/GUM_news_iodine.tsv#L373-L375
  * CoNLL-U format: https://github.com/amir-zeldes/gum/blob/master/dep/GUM_news_iodine.conllu#L417-L419 (notice the annotation -sgl-, indicating it is a singleton)

As for European, it is not included because it is an adjective, but the phrase which contains it, "most European countries", is annotated as a location here:

https://github.com/amir-zeldes/gum/blob/master/dep/GUM_news_iodine.conllu#L421-L423

As for "Food" and "foods", it is possible for singular and plural mentions to corefer, and that is meant to be established based on set-theoretical principles in GUM. In this case I suppose the annotator decided that the compound modifier "food" cannot be pluralized for purely morphological reasons (we don't say "foods standards"), but that the denotation of "food" in "food standards" is in fact identical to "foods" when used to refer to the set of "all edible things". This is indeed something of an edge case and I wouldn't feel confident that all annotators would agree about this, but it is also not out of the question as a correct judgment call.

**Comment by antonyscerri** [comment]
Hi

Thanks for the pointer to the other folder, i hadnt realised there was a difference in what was included, good to know about the singleton cases as well. 

Interesting to see European wasn't included due to it being seen as an adjective. The longer phrase in this case wasn't marked with an entity either, was this due to the inclusion of "most", could not "European countries" have been marked as https://en.wikipedia.org/wiki/European_Union ? 

The instance of Food I was referring to was not a single vs plural case but it simply seemed to be an instance of "food" and not directly coreferent to the Food Standards. For example:

```
20-14   2705-2710       foods   substance[253]  giv:inact[253]  Food[253]       coref   21-8[258_253]
```

Tony

**Comment by amir-zeldes** [comment]
> The longer phrase in this case wasn't marked with an entity either, was this due to the inclusion of "most"

Yes, the criterion is always meant to be set-theoretical: "most European countries" is not a specific subset, and even if we knew the subset, if that specific combination of countries does not have a Wikipedia entry, it would not be wikified.

> it simply seemed to be an instance of "food"

Oh, yes, you're right! Thanks for catching that. I only just noticed this was mistakenly wikified when looking at the data above. This should not have been wikified since it is not really a named entity. The interface proposes all mentions headed by NNP(S) to the annotator, and they should have ignored it here, but instead overzealously linked it to the Wikipedia article on 'food'. I will correct this in the dev branch, and the change will propagate to the public and UD repos on the next release.

**Comment by antonyscerri** [comment]
There may be a couple of other instances of Food in that record that should be removed.

**Comment by amir-zeldes** [comment]
Yes, thanks, I think I got them in a939381
